# config/default_config.yaml
```yaml
data:
  base_dir: "/path/to/your/data"  # Replace with your absolute path
  datasets:
    train:
      div2k:
        path: "DIV2K/train/HR"
        num_images: 100000
        resolution: "2K"
      coco:
        path: "COCO/train2017"
        num_images: 50000
        resolution: "various"
      imagenet:
        path: "ImageNet/validation"
        num_images: 25000
        resolution: "256x256"
    test:
      mit_places:
        path: "MITPlaces/test"
        num_images: 5000
        resolution: "256x256"
      usc_sipi:
        path: "USC-SIPI/misc"
        num_images: 2000
        resolution: "various"
      custom:
        path: "Custom/test"
        num_images: 1000
        resolution: "various"

training:
  batch_size: 32
  num_workers: 4
  epochs: 200
  learning_rate: 0.0001
  save_interval: 10

model:
  image_size: 256
  channels: 3
```